# List of dictionaries to use for spell checking
# Default: ["en_us"]
# Available dictionaries:
#  - English: "en_us", "en_gb"
#  - German: "de", "de_at", "de_ch"
#  - Dutch: "nl_nl"
#  - Spanish: "es"
#  - French: "fr"
#  - Italian: "it"
#  - Russian: "ru"
#  - Swedish: "sv"
dictionaries = ["en_us", "en_gb"]

# Custom allowlist of words to ignore (case-insensitive)
# Codebook will add words here when you select "Add to dictionary"
# Default: []
words = [
	"abdullah","mahmood",
	"codebook",
	"rustc", "omarchy",
	"jupyter", "jupyterlab", "jupytext",
	"ipykernel",
	"scipy",
	"yfinance",
	"plotly",
	"itables",
	"arange",
	"inplace",
	"cumsum",
	"searchsorted",
	"flatnonzero",
	"xaxes","yaxes",
	"xaxis","yaxis",
	"vline",
	"tickformat","dashdot",
	"etf","ETF's",
	"cagr",
	"iloc",
	"dataframe",
	"strftime",
	"ucit","ucits",
	"dotenv",
	"basedpyright",
	"qmd",
	"endsnippet",
	"pyrefly",
	"uv", "uvx", "ruff", "noqa",
	"markdown","quarto","markdownlint",
	"pydantic", "pydantic's",
	"oop",
	"hackathon",
	"zstyle", "eza", "yazi", "fzf", "starship", "ghostty", "autoload", "tmux", "direnv", "envrc", "zoxide"
]

# Words that should always be flagged as incorrect
# Default: []
flag_words = ["todo", "fixme"]

# List of glob patterns for paths to ignore when spell checking
# Default: []
ignore_paths = ["target/**/*", "**/*.json", ".git/**/*"]

# List of regex patterns to ignore when spell checking
# Patterns are matched against each line of text, not individual words
# Useful for domain-specific strings or patterns
# Note: Backslashes must be escaped in TOML (use \\ instead of \)
# Default: []
ignore_patterns = [
    "\\b[ATCG]+\\b",             # DNA sequences
    "\\d{3}-\\d{2}-\\d{4}",      # Social Security Number format
    "^[A-Z]{2,}$",               # All caps words like "HTML", "CSS"
    "https?://[^\\s]+"           # URLs
]

# Minimum word length to check (words shorter than this are ignored)
# Default: 3
# Set to 0 to check all words including single letters
# Set to 2 to check words with 2 or more characters
min_word_length = 3

# Whether to use global configuration (project config only)
# Set to false to completely ignore global settings
# Default: true
use_global = true
