[experimental]

[package_management]
manager = "uv"

[runtime]
reactive_tests = true
watcher_on_save = "lazy"
default_auto_download = []
on_cell_change = "autorun"
auto_reload = "autorun"
default_sql_output = "auto"
auto_instantiate = true
output_max_bytes = 8000000
std_stream_max_bytes = 1000000

[language_servers.ty]
enabled = true

[language_servers.basedpyright]
enabled = true

[language_servers.pylsp]
enable_flake8 = false
enabled = true
enable_pydocstyle = false
enable_pyflakes = false
enable_pylint = false
enable_mypy = true
enable_ruff = true

[diagnostics]

[save]
autosave = "after_delay"
autosave_delay = 10000
format_on_save = false

[ai]
rules = ""
mode = "manual"
inline_tooltip = false

[ai.anthropic]

[ai.google]

[ai.models]
custom_models = []
displayed_models = []

[ai.open_ai]

[completion]
copilot = false
activate_on_typing = true

[keymap]
preset = "default"
destructive_delete = true

[keymap.overrides]

[formatting]
line_length = 79

[server]
browser = "default"
follow_symlink = false

[snippets]
custom_paths = []
include_default_snippets = true

[mcp]
presets = []

[mcp.mcpServers]

[display]
code_editor_font_size = 14
default_table_max_columns = 50
dataframes = "rich"
reference_highlighting = false
theme = "light"
cell_output = "above"
default_table_page_size = 10
default_width = "medium"
