LANG=en_GB.UTF-8
LC_ADDRESS=ar_AE.UTF-8
LC_IDENTIFICATION=ar_AE.UTF-8
LC_MEASUREMENT=ar_AE.UTF-8
LC_MONETARY=ar_AE.UTF-8
LC_NAME=ar_AE.UTF-8
LC_NUMERIC=ar_AE.UTF-8
LC_PAPER=ar_AE.UTF-8
LC_TELEPHONE=ar_AE.UTF-8
LC_TIME=en_GB.UTF-8
